### ISSUE TITLE
Object has no method 'copy' (Buffer API change in Node v4)

### ISSUE THREAD

**Issue by STRML** [socketio/engine.io#356]
```
buffer.js:499
    buf.copy(buffer, pos);
        ^
TypeError: Object  has no method 'copy'
  at Function.Buffer.concat (buffer.js:499:9)
  at IncomingMessage.onData (/dev/node_modules/engine.io/lib/transports/polling.js:147:23)
  at IncomingMessage.EventEmitter.emit (events.js:95:17)
  at IncomingMessage.<anonymous> (_stream_readable.js:746:14)
  at IncomingMessage.EventEmitter.emit (events.js:92:17)
  at emitDataEvents (_stream_readable.js:771:10)
  at IncomingMessage.Readable.on (_stream_readable.js:692:5)
  at XHR.Polling.onDataRequest (/dev/node_modules/engine.io/lib/transports/polling.js:171:7)
  at XHR.Polling.onRequest (/dev/node_modules/engine.io/lib/transports/polling.js:55:10)
  at XHR.onRequest (/dev/node_modules/engine.io/lib/transports/polling-xhr.js:47:33)
  at /dev/node_modules/engine.io/lib/server.js:178:46
  at Server.verify (/dev/node_modules/engine.io/lib/server.js:126:3)
  at Server.handleRequest (/dev/node_modules/engine.io/lib/server.js:170:8)
  at [object Object].request (/dev/node_modules/primus/transformers/engine.io/server.js:59:18)
  at [object Object].emit (/dev/node_modules/primus/node_modules/eventemitter3/index.js:53:12)
  at emit (/dev/node_modules/primus/node_modules/fusing/index.js:131:24)
  at iterate (/dev/node_modules/primus/transformer.js:120:24)
  at done (/dev/node_modules/primus/transformer.js:142:7)
```

This has cropped back up with Node v4 as documented in this Primus ticket: https://github.com/primus/primus/issues/196#issuecomment-146569882

I'm going to try to investigate where this is happening: please see [this comment](https://github.com/nodejs/node/issues/3025#issuecomment-142991417) for more information about the Buffer change in core.

**Comment by episodeyang** [comment]
:+1: ! 

was just about to open one.

**Comment by lpinca** [comment]
@STRML it should be [here](https://github.com/socketio/engine.io/blob/3df49bb86e88fb8a9a144ecfa3fae5ef914909bb/lib/transports/polling.js#L154).

**Comment by STRML** [comment]
Ah I think I know how this happens:

The `'data'` listener must be called with `null` at some point while not in Binary mode.

Because the 'data' is not a string, this calls `Buffer.concat(['', null])` which throws the error.

A fix for this should simply be a `if (!data) return` at the beginning of the 'data' listener, because even in Binary mode this would cause a problem (`Buffer.concat([new Buffer(0), null])` throws `cannot read property 'length' of null`).

**Comment by STRML** [comment]
Is it possible for binary (Buffer) data to come through the connection even though the content type is not set to `'application/octet-stream'`?

**Comment by lpinca** [comment]
We are disabling [binary](https://github.com/primus/primus/blob/c2020f899b18507abc188d66dcefa4200775db8e/transformers/engine.io/client.js#L62) support in primus so binary data should not come in.

**Comment by lpinca** [comment]
@STRML there is an open pr exactly for what you are describing (#305) but it's odd.

**Comment by STRML** [comment]
Just saw this today on an instance running `v4.1.2`:

```
TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:238:9)
    at IncomingMessage.onData (/srv/api/node_modules/engine.io/lib/transports/polling.js:147:23)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:733:26)
    at resume_ (_stream_readable.js:713:3)
    ...
```

**Comment by necccc** [comment]
Saw this with 4.2.2 too, when used with primus

**buf.copy is not a function**
```
/buffer.js:238 → Function.Buffer.concat
/server/node_modules/engine.io/lib/transports/polling.js:147 → IncomingMessage.onData
/events.js:77 → emitOne
/events.js:169 → IncomingMessage.emit
/_stream_readable.js:360 → IncomingMessage.Readable.read
/_stream_readable.js:743 → flow
/_stream_readable.js:723 → resume_
/node.js:441 → doNTCallback2
/node.js:355 → process._tickCallback
```

**Comment by lpinca** [comment]
@necccc this has been fixed in https://github.com/socketio/engine.io/pull/305#issuecomment-157184323. We have to wait for the next version of Engine.IO.

**Comment by noamshemesh** [comment]
still happens, even after upgrading to primus 4.0.4 and engine.io 1.6.4
any ideas?

**Comment by lpinca** [comment]
@noamshemesh that's weird, do you have a way to reproduce it?

**Comment by noamshemesh** [comment]
we stream data from the db and send it with [primus function `spark.write`](https://github.com/primus/primus#sparkwritedata)
it works well for almost all the times but when there is a lot of data to stream it's crashing with this error:
```
TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:238:9)
    at IncomingMessage.onData (/opt/bigpanda/web-api/node_modules/engine.io/lib/transports/polling.js:160:23)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
...(wrappers)...
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:743:26)
    at resume_ (_stream_readable.js:723:3)
```

**Comment by lpinca** [comment]
@noamshemesh please also open a new issue on Primus or continue here: https://github.com/primus/primus/issues/196.

**Comment by noamshemesh** [comment]
I enabled DEUBG=engine:polling logs and just before it crashed the debug lines are:
```
engine:polling setting request +5s 
engine:polling received "21:4{"type":"subscribe"}" +183ms
engine:polling writing "1:6" +167ms
```

does it help?

**Comment by noamshemesh** [comment]
ok after some more debugging it seems like it crashes when the server receives a big buffer from the client. not sure why the buffer doesn't have the copy function

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/305
